version: '3.7'
services:
  flight-management-app:
    build:
      context: .
    container_name: assignment-service
    image: nazarovv2/assignment-service:latest
    ports:
      - "80:80"
    networks:
      - net
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECURITY_TOKEN_ACCESS_SECRET_KEY=${SECURITY_TOKEN_ACCESS_SECRET_KEY}
      - SECURITY_TOKEN_ACCESS_TIME=${SECURITY_TOKEN_ACCESS_TIME}
      - SECURITY_TOKEN_REFRESH_SECRET_KEY=${SECURITY_TOKEN_REFRESH_SECRET_KEY}
      - SECURITY_TOKEN_REFRESH_TIME=${SECURITY_TOKEN_REFRESH_TIME}
      - AWS_CREDENTIALS_ACCESS_KEY=${AWS_CREDENTIALS_ACCESS_KEY}
      - AWS_CREDENTIALS_SECRET_KEY=${AWS_CREDENTIALS_SECRET_KEY}
      - AWS_S3_BUCKET_REGION_STATIC=${AWS_S3_BUCKET_REGION_STATIC}
      - AWS_S3_BUCKET_STACK_AUTO=${AWS_S3_BUCKET_STACK_AUTO}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
networks:
  net:
    driver: "bridge"
